### ISSUE TITLE
Private repo?

### ISSUE THREAD

**Issue by matthew-white** [PovertyAction/Peru-Trust-Games#1]
Should this be a private repo? Either way, the owner should probably be PovertyAction, right?

**Comment by mdieci** [comment]
Yes, this was leftover from last year when we were testing out GitHub and I
made an account with this first data repo project. IPA should be the owner
now.

On Wed, Jan 21, 2015 at 4:19 PM, Matthew White notifications@github.com
wrote:

> Should this be a private repo? Either way, the owner should probably be
> PovertyAction, right?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mdieci/Peru-Trust-Games/issues/1.

## 

Maria Dieci | Research Analyst | Innovations for Poverty Action
mdieci@poverty-action.org  | Skype maria.dieci | +1-404-626-8491
